[pytest]
python_paths = backend/
DJANGO_SETTINGS_MODULE = kittygram_backend.settings
norecursedirs = env/*
addopts = -vv -p no:cacheprovider -p no:pytest_cov -p no:faker -p no:lazy-fixture -p no:xdist -p no:xdist.looponfail --disable-warnings --ignore=tests/test_connection.py
testpaths = tests/
python_files = test_*.py
